"""Add added_by column to tags table

Revision ID: 26a7bab020d5
Revises: b428bda59f9e
Create Date: 2026-06-15 02:53:22.448534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a7bab020d5'
down_revision: Union[str, Sequence[str], None] = 'b428bda59f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tags', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'owner_id')
    # ### end Alembic commands ###
